### ISSUE TITLE
Ethernet connection / MQTT

### ISSUE THREAD

**Issue by sbernhard** [raibisch/ESP32_ABL#4]
Thanks. Very nice project. My EMH1 will arrive in some days and hopefully I can usw this small addition.

You asked if MQTT would be nice: yes. Greatest way to set and get variables with standard API for home automation systems. Additionally, it would help to store the really messured consumption from your smart meter. I will use a SDM72 but for me it is not necessary to have this data on this project as it is only used to control the Wallbox itself and get the Wallbox values to my home automation system.

I want to use Ethernet instead of WiFi. Does this work? 

Additionally, as the board is pretty small and only a rs485 connection to the Wallbox is necessary, it would be pretty nice to put the esp/board components in the Wallbox itself.

**Comment by raibisch** [comment]
Hi sbernhard,

thanks, for your comment and suggestions,

MQTT is on my list (...but be patient, because its a free time project)
possible libs to integrate this function:
https://github.com/knolleary/pubsubclient
https://github.com/256dpi/arduino-mqtt
...maybe you (or others) have interest to add these function ;-)

Ethernet on the ESP32 would be possible, but required additional hardware (here I found a "ready to use" ESP32 board: https://www.roboter-bausatz.de/p/wt32-eth01-esp32-modul-mit-ethernet-bluetooth-wifi)...but this is definitely out of my focus for further developments. 

your suggestion for placing the ESP32 into the Wallbox: yes this is also possible, then you need a 5V power-supply in the Wallbox (...or connect it from outside into the Wallbox). 

A third (and forth) possibility is to us a long RS485 wired connection (this should work up to 100m with 9600Bd)  into the house and place the ESP32 near your WiFi-router,  or to place a small WiFi-to-Ethernet gateway near your Wallbox.

**Comment by sbernhard** [comment]
Thanks for you response.

I bought a Olimex LAN PoE ESP: https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware

Hopefully this one works after some adaptions.

Then I need to use an API to control everything - or it will be MQTT 😀

Would be nice if we can work together and integrate the support of this POE ESP.

**Comment by Meins321** [comment]
Mqtt would be nice to have but maybe we need a single pin input to reduce below <4,6KW charge power as this will be the rule from 1.1.2024 in Germany....
Many people will dispose the ABL wallboxes if they can't be reduced in power by the network supplier :-/

**Comment by raibisch** [comment]
just an idea:
Would it be usefull to have a default startup (after power-on and reset) value at 6A  (3phase =230V*6*3=4140W) or 10A (2phase =230*10*2=4600W)
(could be a setting variable in the config section)

**Give me an response.**
if this is usefull I will integrate this in the next release!

**Comment by raibisch** [comment]
...some infos (in a german forum)
to say it in german: das ist nicht wirklich ein Problem !
[https://www.goingelectric.de/forum/viewtopic.php?t=30783](https://www.goingelectric.de/forum/viewtopic.php?t=30783)

**Comment by sbernhard** [comment]
> just an idea: Would it be usefull to have a default startup (after power-on and reset) value at 6A (3phase =230V_6_3=4140W) or 10A (2phase =230_10_2=4600W) (could be a setting variable in the config section)
> 
> **Give me an response.** if this is usefull I will integrate this in the next release!

I normally like, that it use the same setting as at the previous charging session.

**Comment by raibisch** [comment]
Hallo Bernhard,
kannst du die Anpassung in deinen Fork auf GitHub integrieren ?
Ich hab ein ESP32 Ethernet Board (WT32-S1) bestellt um den Fork zu testen.

**Comment by sbernhard** [comment]
> Hallo Bernhard, kannst du die Anpassung in deinen Fork auf GitHub integrieren ? Ich hab ein ESP32 Ethernet Board (WT32-S1) bestellt um den Fork zu testen.

HIer findest du den PR: https://github.com/raibisch/ESP32_ABL/pull/8
Und hier den Fork: https://github.com/sbernhard/ESP32_ABL/tree/add_ethernet
